name: "VEX V5 Blocks Build"
description: "Build VEX V5 Blocks project."
branding:
  icon: "terminal"
  color: "gray-dark"
inputs:
  path:
    description: "Path and filename to file"
    required: true
    default: "MyProject.v5blocks"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
